In [10]:
#Import Dependencies
import pandas as pd
import numpy as np

In [11]:
file = "Resources/listings.csv"

df = pd.read_csv(file)
columns_to_keep = ["zipcode", "room_type", "accommodates", "bedrooms", "bathrooms", "beds", "minimum_nights", "number_of_reviews", "price"]
df = df[columns_to_keep]

#drop all rows with nulls
df.dropna(how='any', inplace=True)

#make copy of df to avoid warning errors
data_df = df.copy()

# price is a string.  Remove $ and convert into float
# https://stackoverflow.com/questions/32464280/converting-currency-with-to-numbers-in-python-pandas
data_df["price"] = data_df["price"].replace('[\$,]', '', regex=True).astype(float)

#there is one row where they have "CA" for zipcode.  Drop that row.
data_df=data_df[data_df.zipcode != "CA"]

#drop hotel room from room_type
data_df=data_df[data_df.room_type != "Hotel room"]

#some zipcodes start with CA.  replace "CA " with "" 
#https://stackoverflow.com/questions/13682044/remove-unwanted-parts-from-strings-in-a-column
data_df["zipcode"] = data_df["zipcode"].replace('CA ', '', regex=True)

#drop all rows with nulls
data_df.dropna(how='any', inplace=True)

#convert zipcodes to intergers 
data_df["zipcode"] = data_df["zipcode"].astype(str).astype(int)

#we only want to keep prices below $500.  Everything about $500 is an outlier
data_df = data_df[data_df.price < 500]

data_df.head()

,zipcode,room_type,accommodates,bedrooms,bathrooms,beds,minimum_nights,number_of_reviews,price
0,94117,Entire home/apt,3,1.0,1.0,2.0,1,240,170.0
1,94110,Entire home/apt,5,2.0,1.0,3.0,30,111,235.0
2,94117,Private room,2,1.0,4.0,1.0,32,19,65.0
3,94117,Private room,2,1.0,4.0,1.0,32,8,65.0
5,94110,Private room,3,1.0,1.0,1.0,1,736,139.0

In [12]:
data_df.dtypes

zipcode                int32
room_type             object
accommodates           int64
bedrooms             float64
bathrooms            float64
beds                 float64
minimum_nights         int64
number_of_reviews      int64
price                float64
dtype: object

In [13]:
##### create price bins.  TA recommends 7 - 15 bins.  each bin is an increment of $50
bins = [0]
bin_names = []

for i in range (0,10):
    x = (i * 50) + 50
    bins.append(x)
    name = "bin " + str(i*50) + "-" + str(x)
    bin_names.append(name)
    
print(bins, bin_names)
print(len(bins), len(bin_names))

[0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500] ['bin 0-50', 'bin 50-100', 'bin 100-150', 'bin 150-200', 'bin 200-250', 'bin 250-300', 'bin 300-350', 'bin 350-400', 'bin 400-450', 'bin 450-500']
11 10

In [14]:
#cut the bins and group names to the dataframe

data_df["price_bin"] = pd.cut(data_df["price"], bins, labels=bin_names)
data_df.head(25)

,zipcode,room_type,accommodates,bedrooms,bathrooms,beds,minimum_nights,number_of_reviews,price,price_bin
0,94117,Entire home/apt,3,1.0,1.0,2.0,1,240,170.0,bin 150-200
1,94110,Entire home/apt,5,2.0,1.0,3.0,30,111,235.0,bin 200-250
2,94117,Private room,2,1.0,4.0,1.0,32,19,65.0,bin 50-100
3,94117,Private room,2,1.0,4.0,1.0,32,8,65.0,bin 50-100
5,94110,Private room,3,1.0,1.0,1.0,1,736,139.0,bin 100-150
6,94107,Private room,2,1.0,1.0,1.0,1,531,135.0,bin 100-150
7,94110,Entire home/apt,4,2.0,1.0,3.0,30,337,150.0,bin 100-150
8,94109,Entire home/apt,2,0.0,1.0,1.0,30,18,120.0,bin 100-150
9,94117,Entire home/apt,3,3.0,1.0,3.0,30,37,177.0,bin 150-200
10,94102,Entire home/apt,5,3.0,2.0,3.0,30,15,110.0,bin 100-150
11,94102,Entire home/apt,2,1.0,1.5,1.0,30,20,121.0,bin 100-150
12,94117,Private room,2,1.0,3.0,2.0,32,6,85.0,bin 50-100
13,94117,Private room,2,1.0,3.0,2.0,32,5,85.0,bin 50-100
14,94114,Private room,1,1.0,1.0,1.0,3,427,79.0,bin 50-100
15,94117,Entire home/apt,4,2.0,1.0,3.0,30,17,117.0,bin 100-150
16,94105,Entire home/apt,4,2.0,2.0,2.0,30,14,450.0,bin 400-450
17,94114,Entire home/apt,3,0.0,1.0,1.0,30,63,107.0,bin 100-150
18,94117,Private room,2,1.0,1.0,1.0,2,415,110.0,bin 100-150
19,94133,Entire home/apt,2,1.0,1.0,1.0,30,119,125.0,bin 100-150
20,94117,Private room,2,1.0,4.0,1.0,32,14,65.0,bin 50-100
21,94114,Entire home/apt,2,1.0,1.0,1.0,3,412,155.0,bin 150-200
22,94107,Private room,2,1.0,1.0,1.0,2,306,135.0,bin 100-150
23,94117,Private room,1,1.0,1.0,1.0,1,204,79.0,bin 50-100
24,94115,Entire home/apt,4,1.0,1.0,1.0,5,332,225.0,bin 200-250
25,94131,Private room,2,1.0,1.0,1.0,5,42,150.0,bin 100-150

In [15]:
data_df.to_csv("Output/cleaned_data_bin_50.csv", index = False)